// Mocks generated by Mockito 5.4.6 from annotations
// in redmaestra1/test/login_screen_test_simple.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:redmaestra1/domain/entities/user_entity.dart' as _i3;
import 'package:redmaestra1/domain/repositories/auth_repository.dart' as _i2;
import 'package:redmaestra1/domain/usecases/auth/get_current_user_usecase.dart'
    as _i7;
import 'package:redmaestra1/domain/usecases/auth/login_usecase.dart' as _i4;
import 'package:redmaestra1/domain/usecases/auth/register_usecase.dart' as _i6;
import 'package:redmaestra1/domain/usecases/auth/update_user_usecase.dart'
    as _i9;
import 'package:redmaestra1/domain/usecases/usecase.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i4.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.UserEntity> call(_i4.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(this, Invocation.method(#call, [params])),
            ),
          )
          as _i5.Future<_i3.UserEntity>);
}

/// A class which mocks [RegisterUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUsecase extends _i1.Mock implements _i6.RegisterUsecase {
  MockRegisterUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.UserEntity> call(_i6.RegisterParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(this, Invocation.method(#call, [params])),
            ),
          )
          as _i5.Future<_i3.UserEntity>);
}

/// A class which mocks [GetCurrentUserUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUsecase extends _i1.Mock
    implements _i7.GetCurrentUserUsecase {
  MockGetCurrentUserUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.UserEntity?> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.UserEntity?>.value(),
          )
          as _i5.Future<_i3.UserEntity?>);
}

/// A class which mocks [UpdateUserUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserUsecase extends _i1.Mock implements _i9.UpdateUserUsecase {
  MockUpdateUserUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<void> call(_i3.UserEntity? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
